# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_project.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_create_new_project(object):
    def setupUi(self, create_new_project):
        create_new_project.setObjectName("create_new_project")
        create_new_project.setWindowModality(QtCore.Qt.ApplicationModal)
        create_new_project.setMinimumSize(QtCore.QSize(550, 500))
        create_new_project.setAutoFillBackground(False)
        create_new_project.setModal(True)
        create_new_project.setWizardStyle(QtWidgets.QWizard.ClassicStyle)
        create_new_project.setOptions(QtWidgets.QWizard.NoBackButtonOnLastPage|QtWidgets.QWizard.NoBackButtonOnStartPage)
        self.newp_p1 = QtWidgets.QWizardPage()
        self.newp_p1.setObjectName("newp_p1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.newp_p1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newp_p1_title = QtWidgets.QLabel(self.newp_p1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newp_p1_title.setFont(font)
        self.newp_p1_title.setObjectName("newp_p1_title")
        self.verticalLayout.addWidget(self.newp_p1_title)
        self.newp_p1_layout = QtWidgets.QFormLayout()
        self.newp_p1_layout.setContentsMargins(-1, 8, -1, -1)
        self.newp_p1_layout.setObjectName("newp_p1_layout")
        self.newp_projectname_label = QtWidgets.QLabel(self.newp_p1)
        self.newp_projectname_label.setObjectName("newp_projectname_label")
        self.newp_p1_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.newp_projectname_label)
        self.newp_projectname_input = QtWidgets.QLineEdit(self.newp_p1)
        self.newp_projectname_input.setObjectName("newp_projectname_input")
        self.newp_p1_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.newp_projectname_input)
        self.verticalLayout.addLayout(self.newp_p1_layout)
        self.newp_ldir_label = QtWidgets.QLabel(self.newp_p1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.newp_ldir_label.setFont(font)
        self.newp_ldir_label.setText("")
        self.newp_ldir_label.setObjectName("newp_ldir_label")
        self.verticalLayout.addWidget(self.newp_ldir_label)
        create_new_project.addPage(self.newp_p1)
        self.newp_p2 = QtWidgets.QWizardPage()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newp_p2.sizePolicy().hasHeightForWidth())
        self.newp_p2.setSizePolicy(sizePolicy)
        self.newp_p2.setObjectName("newp_p2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.newp_p2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newp_p2_add_video_title = QtWidgets.QLabel(self.newp_p2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newp_p2_add_video_title.setFont(font)
        self.newp_p2_add_video_title.setObjectName("newp_p2_add_video_title")
        self.verticalLayout_2.addWidget(self.newp_p2_add_video_title)
        self.newp_p2_add_vido_description = QtWidgets.QLabel(self.newp_p2)
        self.newp_p2_add_vido_description.setWordWrap(True)
        self.newp_p2_add_vido_description.setObjectName("newp_p2_add_vido_description")
        self.verticalLayout_2.addWidget(self.newp_p2_add_vido_description)
        self.newp_p2_video_layout = QtWidgets.QFormLayout()
        self.newp_p2_video_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.newp_p2_video_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.newp_p2_video_layout.setObjectName("newp_p2_video_layout")
        self.newp_video_label = QtWidgets.QLabel(self.newp_p2)
        self.newp_video_label.setMinimumSize(QtCore.QSize(0, 28))
        self.newp_video_label.setObjectName("newp_video_label")
        self.newp_p2_video_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.newp_video_label)
        self.newp_p2_video_browse_layout = QtWidgets.QHBoxLayout()
        self.newp_p2_video_browse_layout.setObjectName("newp_p2_video_browse_layout")
        self.newp_video_input = QtWidgets.QLineEdit(self.newp_p2)
        self.newp_video_input.setMinimumSize(QtCore.QSize(0, 21))
        self.newp_video_input.setObjectName("newp_video_input")
        self.newp_p2_video_browse_layout.addWidget(self.newp_video_input)
        self.newp_video_browse = QtWidgets.QPushButton(self.newp_p2)
        self.newp_video_browse.setMinimumSize(QtCore.QSize(0, 32))
        self.newp_video_browse.setObjectName("newp_video_browse")
        self.newp_p2_video_browse_layout.addWidget(self.newp_video_browse)
        self.newp_p2_video_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.newp_p2_video_browse_layout)
        self.newp_video_start_time_label = QtWidgets.QLabel(self.newp_p2)
        self.newp_video_start_time_label.setMinimumSize(QtCore.QSize(0, 24))
        self.newp_video_start_time_label.setObjectName("newp_video_start_time_label")
        self.newp_p2_video_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.newp_video_start_time_label)
        self.newp_video_start_time_input = QtWidgets.QDateTimeEdit(self.newp_p2)
        self.newp_video_start_time_input.setMinimumSize(QtCore.QSize(0, 24))
        self.newp_video_start_time_input.setObjectName("newp_video_start_time_input")
        self.newp_p2_video_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.newp_video_start_time_input)
        self.newp_video_server_label = QtWidgets.QLabel(self.newp_p2)
        self.newp_video_server_label.setMinimumSize(QtCore.QSize(0, 21))
        self.newp_video_server_label.setObjectName("newp_video_server_label")
        self.newp_p2_video_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.newp_video_server_label)
        self.newp_video_server_input = QtWidgets.QLineEdit(self.newp_p2)
        self.newp_video_server_input.setMinimumSize(QtCore.QSize(0, 21))
        self.newp_video_server_input.setObjectName("newp_video_server_input")
        self.newp_p2_video_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.newp_video_server_input)
        self.newp_video_email_label = QtWidgets.QLabel(self.newp_p2)
        self.newp_video_email_label.setMinimumSize(QtCore.QSize(0, 21))
        self.newp_video_email_label.setObjectName("newp_video_email_label")
        self.newp_p2_video_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.newp_video_email_label)
        self.newp_video_email_input = QtWidgets.QLineEdit(self.newp_p2)
        self.newp_video_email_input.setMinimumSize(QtCore.QSize(0, 21))
        self.newp_video_email_input.setObjectName("newp_video_email_input")
        self.newp_p2_video_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.newp_video_email_input)
        self.verticalLayout_2.addLayout(self.newp_p2_video_layout)
        self.newp_add_aerial_image_title = QtWidgets.QLabel(self.newp_p2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newp_add_aerial_image_title.setFont(font)
        self.newp_add_aerial_image_title.setObjectName("newp_add_aerial_image_title")
        self.verticalLayout_2.addWidget(self.newp_add_aerial_image_title)
        self.newp_p2_add_aerial_image_description = QtWidgets.QLabel(self.newp_p2)
        self.newp_p2_add_aerial_image_description.setWordWrap(True)
        self.newp_p2_add_aerial_image_description.setObjectName("newp_p2_add_aerial_image_description")
        self.verticalLayout_2.addWidget(self.newp_p2_add_aerial_image_description)
        self.newp_p2_aerial_layout = QtWidgets.QFormLayout()
        self.newp_p2_aerial_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.newp_p2_aerial_layout.setContentsMargins(-1, 8, -1, -1)
        self.newp_p2_aerial_layout.setObjectName("newp_p2_aerial_layout")
        self.newp_aerial_image_label = QtWidgets.QLabel(self.newp_p2)
        self.newp_aerial_image_label.setObjectName("newp_aerial_image_label")
        self.newp_p2_aerial_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.newp_aerial_image_label)
        self.newp_p2_image_browse_layout = QtWidgets.QHBoxLayout()
        self.newp_p2_image_browse_layout.setObjectName("newp_p2_image_browse_layout")
        self.newp_aerial_image_input = QtWidgets.QLineEdit(self.newp_p2)
        self.newp_aerial_image_input.setObjectName("newp_aerial_image_input")
        self.newp_p2_image_browse_layout.addWidget(self.newp_aerial_image_input)
        self.newp_aerial_image_browse = QtWidgets.QPushButton(self.newp_p2)
        self.newp_aerial_image_browse.setObjectName("newp_aerial_image_browse")
        self.newp_p2_image_browse_layout.addWidget(self.newp_aerial_image_browse)
        self.newp_p2_aerial_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.newp_p2_image_browse_layout)
        self.verticalLayout_2.addLayout(self.newp_p2_aerial_layout)
        create_new_project.addPage(self.newp_p2)
        self.newp_p3 = QtWidgets.QWizardPage()
        self.newp_p3.setObjectName("newp_p3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.newp_p3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.newp_p2_add_video_title_2 = QtWidgets.QLabel(self.newp_p3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newp_p2_add_video_title_2.setFont(font)
        self.newp_p2_add_video_title_2.setObjectName("newp_p2_add_video_title_2")
        self.verticalLayout_3.addWidget(self.newp_p2_add_video_title_2)
        self.line = QtWidgets.QFrame(self.newp_p3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.newp_start_creation = QtWidgets.QPushButton(self.newp_p3)
        self.newp_start_creation.setObjectName("newp_start_creation")
        self.verticalLayout_3.addWidget(self.newp_start_creation)
        self.newp_creation_progress = QtWidgets.QProgressBar(self.newp_p3)
        self.newp_creation_progress.setProperty("value", 0)
        self.newp_creation_progress.setObjectName("newp_creation_progress")
        self.verticalLayout_3.addWidget(self.newp_creation_progress)
        self.newp_creation_status = QtWidgets.QLabel(self.newp_p3)
        self.newp_creation_status.setObjectName("newp_creation_status")
        self.verticalLayout_3.addWidget(self.newp_creation_status)
        create_new_project.addPage(self.newp_p3)

        self.retranslateUi(create_new_project)
        QtCore.QMetaObject.connectSlotsByName(create_new_project)

    def retranslateUi(self, create_new_project):
        _translate = QtCore.QCoreApplication.translate
        create_new_project.setWindowTitle(_translate("create_new_project", "Create New Project"))
        self.newp_p1_title.setText(_translate("create_new_project", "New Safety Project"))
        self.newp_projectname_label.setText(_translate("create_new_project", "Project Name"))
        self.newp_p2_add_video_title.setText(_translate("create_new_project", "Add project video"))
        self.newp_p2_add_vido_description.setText(_translate("create_new_project", "Browse and select a video file to analyze. Please input the time when the video recording occurred. You may optionally enter an email that should be notified when long-running analysis is finished. You should also enter the IP address or URL of the server that should be used for analysis."))
        self.newp_video_label.setText(_translate("create_new_project", "Selected video"))
        self.newp_video_browse.setText(_translate("create_new_project", "Browse..."))
        self.newp_video_start_time_label.setText(_translate("create_new_project", "Recording start time"))
        self.newp_video_server_label.setText(_translate("create_new_project", "Server IP or URL"))
        self.newp_video_email_label.setText(_translate("create_new_project", "Email"))
        self.newp_add_aerial_image_title.setText(_translate("create_new_project", "Add aerial image"))
        self.newp_p2_add_aerial_image_description.setText(_translate("create_new_project", "Browse and select an aerial image of the video\'s target. "))
        self.newp_aerial_image_label.setText(_translate("create_new_project", "Aerial image"))
        self.newp_aerial_image_browse.setText(_translate("create_new_project", "Browse..."))
        self.newp_p2_add_video_title_2.setText(_translate("create_new_project", "Creating new project"))
        self.newp_start_creation.setText(_translate("create_new_project", "Click to create project."))
        self.newp_creation_status.setText(_translate("create_new_project", "Beginning project creation..."))

