# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/safety_main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TransportationSafety(object):
    def setupUi(self, TransportationSafety):
        TransportationSafety.setObjectName("TransportationSafety")
        TransportationSafety.resize(1280, 800)
        self.centralWidget = QtWidgets.QWidget(TransportationSafety)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_tab_widget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab_widget.sizePolicy().hasHeightForWidth())
        self.main_tab_widget.setSizePolicy(sizePolicy)
        self.main_tab_widget.setAcceptDrops(False)
        self.main_tab_widget.setAutoFillBackground(False)
        self.main_tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main_tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.main_tab_widget.setTabsClosable(False)
        self.main_tab_widget.setObjectName("main_tab_widget")
        self.tab_homography = QtWidgets.QWidget()
        self.tab_homography.setObjectName("tab_homography")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_homography)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.control_box = QtWidgets.QFrame(self.tab_homography)
        self.control_box.setMinimumSize(QtCore.QSize(0, 40))
        self.control_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_box.setObjectName("control_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.control_box)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.open_buttons = QtWidgets.QHBoxLayout()
        self.open_buttons.setContentsMargins(11, 11, 11, 11)
        self.open_buttons.setSpacing(6)
        self.open_buttons.setObjectName("open_buttons")
        self.homography_button_open_camera_image = QtWidgets.QPushButton(self.control_box)
        self.homography_button_open_camera_image.setObjectName("homography_button_open_camera_image")
        self.open_buttons.addWidget(self.homography_button_open_camera_image)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.open_buttons.addItem(spacerItem)
        self.homography_button_open_aerial_image = QtWidgets.QPushButton(self.control_box)
        self.homography_button_open_aerial_image.setObjectName("homography_button_open_aerial_image")
        self.open_buttons.addWidget(self.homography_button_open_aerial_image)
        self.verticalLayout_4.addLayout(self.open_buttons)
        self.zoom_sliders = QtWidgets.QHBoxLayout()
        self.zoom_sliders.setContentsMargins(11, 11, 11, 11)
        self.zoom_sliders.setSpacing(6)
        self.zoom_sliders.setObjectName("zoom_sliders")
        self.homography_label_zoom_camera_image = QtWidgets.QLabel(self.control_box)
        self.homography_label_zoom_camera_image.setObjectName("homography_label_zoom_camera_image")
        self.zoom_sliders.addWidget(self.homography_label_zoom_camera_image)
        self.homography_hslider_zoom_camera_image = ZoomSlider(self.control_box)
        self.homography_hslider_zoom_camera_image.setMinimum(10)
        self.homography_hslider_zoom_camera_image.setMaximum(400)
        self.homography_hslider_zoom_camera_image.setPageStep(25)
        self.homography_hslider_zoom_camera_image.setProperty("value", 100)
        self.homography_hslider_zoom_camera_image.setOrientation(QtCore.Qt.Horizontal)
        self.homography_hslider_zoom_camera_image.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.homography_hslider_zoom_camera_image.setTickInterval(0)
        self.homography_hslider_zoom_camera_image.setObjectName("homography_hslider_zoom_camera_image")
        self.zoom_sliders.addWidget(self.homography_hslider_zoom_camera_image)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.zoom_sliders.addItem(spacerItem1)
        self.homography_label_zoom_computed_image = QtWidgets.QLabel(self.control_box)
        self.homography_label_zoom_computed_image.setObjectName("homography_label_zoom_computed_image")
        self.zoom_sliders.addWidget(self.homography_label_zoom_computed_image)
        self.homography_hslider_zoom_computed_image = ZoomSlider(self.control_box)
        self.homography_hslider_zoom_computed_image.setMinimum(10)
        self.homography_hslider_zoom_computed_image.setMaximum(400)
        self.homography_hslider_zoom_computed_image.setPageStep(25)
        self.homography_hslider_zoom_computed_image.setProperty("value", 100)
        self.homography_hslider_zoom_computed_image.setOrientation(QtCore.Qt.Horizontal)
        self.homography_hslider_zoom_computed_image.setObjectName("homography_hslider_zoom_computed_image")
        self.zoom_sliders.addWidget(self.homography_hslider_zoom_computed_image)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.zoom_sliders.addItem(spacerItem2)
        self.homography_label_zoom_aerial_image = QtWidgets.QLabel(self.control_box)
        self.homography_label_zoom_aerial_image.setObjectName("homography_label_zoom_aerial_image")
        self.zoom_sliders.addWidget(self.homography_label_zoom_aerial_image)
        self.homography_hslider_zoom_aerial_image = ZoomSlider(self.control_box)
        self.homography_hslider_zoom_aerial_image.setMinimum(10)
        self.homography_hslider_zoom_aerial_image.setMaximum(400)
        self.homography_hslider_zoom_aerial_image.setPageStep(25)
        self.homography_hslider_zoom_aerial_image.setProperty("value", 100)
        self.homography_hslider_zoom_aerial_image.setOrientation(QtCore.Qt.Horizontal)
        self.homography_hslider_zoom_aerial_image.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.homography_hslider_zoom_aerial_image.setObjectName("homography_hslider_zoom_aerial_image")
        self.zoom_sliders.addWidget(self.homography_hslider_zoom_aerial_image)
        self.verticalLayout_4.addLayout(self.zoom_sliders)
        self.homography_status_layout = QtWidgets.QHBoxLayout()
        self.homography_status_layout.setContentsMargins(11, 0, 11, 11)
        self.homography_status_layout.setSpacing(6)
        self.homography_status_layout.setObjectName("homography_status_layout")
        self.homography_camera_status_label = QtWidgets.QLabel(self.control_box)
        self.homography_camera_status_label.setText("")
        self.homography_camera_status_label.setObjectName("homography_camera_status_label")
        self.homography_status_layout.addWidget(self.homography_camera_status_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.homography_status_layout.addItem(spacerItem3)
        self.homography_aerial_status_label = QtWidgets.QLabel(self.control_box)
        self.homography_aerial_status_label.setText("")
        self.homography_aerial_status_label.setObjectName("homography_aerial_status_label")
        self.homography_status_layout.addWidget(self.homography_aerial_status_label)
        self.verticalLayout_4.addLayout(self.homography_status_layout)
        self.verticalLayout.addWidget(self.control_box)
        self.homography_layout = QtWidgets.QHBoxLayout()
        self.homography_layout.setContentsMargins(11, 11, 11, 11)
        self.homography_layout.setSpacing(6)
        self.homography_layout.setObjectName("homography_layout")
        self.homography_cameraview = HomographyView(self.tab_homography)
        self.homography_cameraview.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.homography_cameraview.setMouseTracking(True)
        self.homography_cameraview.setObjectName("homography_cameraview")
        self.homography_layout.addWidget(self.homography_cameraview)
        self.homography_results = HomographyResultView(self.tab_homography)
        self.homography_results.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.homography_results.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.homography_results.setObjectName("homography_results")
        self.homography_layout.addWidget(self.homography_results)
        self.homography_aerialview = HomographyView(self.tab_homography)
        self.homography_aerialview.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.homography_aerialview.setMouseTracking(True)
        self.homography_aerialview.setObjectName("homography_aerialview")
        self.homography_layout.addWidget(self.homography_aerialview)
        self.verticalLayout.addLayout(self.homography_layout)
        self.homography_flow_control = QtWidgets.QWidget(self.tab_homography)
        self.homography_flow_control.setMinimumSize(QtCore.QSize(0, 50))
        self.homography_flow_control.setObjectName("homography_flow_control")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.homography_flow_control)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.homography_label_notification = QtWidgets.QLabel(self.homography_flow_control)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.homography_label_notification.setFont(font)
        self.homography_label_notification.setText("")
        self.homography_label_notification.setObjectName("homography_label_notification")
        self.horizontalLayout_2.addWidget(self.homography_label_notification)
        self.unit_px_label = QtWidgets.QLabel(self.homography_flow_control)
        self.unit_px_label.setObjectName("unit_px_label")
        self.horizontalLayout_2.addWidget(self.unit_px_label)
        self.unit_px_input = QtWidgets.QLineEdit(self.homography_flow_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unit_px_input.sizePolicy().hasHeightForWidth())
        self.unit_px_input.setSizePolicy(sizePolicy)
        self.unit_px_input.setObjectName("unit_px_input")
        self.horizontalLayout_2.addWidget(self.unit_px_input)
        self.unit_px_label2 = QtWidgets.QLabel(self.homography_flow_control)
        self.unit_px_label2.setObjectName("unit_px_label2")
        self.horizontalLayout_2.addWidget(self.unit_px_label2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.homography_compute_button = QtWidgets.QPushButton(self.homography_flow_control)
        self.homography_compute_button.setObjectName("homography_compute_button")
        self.horizontalLayout_2.addWidget(self.homography_compute_button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.homography_continue_button = QtWidgets.QPushButton(self.homography_flow_control)
        self.homography_continue_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.homography_continue_button.setObjectName("homography_continue_button")
        self.horizontalLayout_2.addWidget(self.homography_continue_button)
        self.verticalLayout.addWidget(self.homography_flow_control)
        self.main_tab_widget.addTab(self.tab_homography, "")
        self.tab_features = QtWidgets.QWidget()
        self.tab_features.setObjectName("tab_features")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_features)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.feature_tracking_run_panel = QtWidgets.QWidget(self.tab_features)
        self.feature_tracking_run_panel.setObjectName("feature_tracking_run_panel")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.feature_tracking_run_panel)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.feature_tracking_run_test_progress = QtWidgets.QProgressBar(self.feature_tracking_run_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feature_tracking_run_test_progress.sizePolicy().hasHeightForWidth())
        self.feature_tracking_run_test_progress.setSizePolicy(sizePolicy)
        self.feature_tracking_run_test_progress.setProperty("value", 0)
        self.feature_tracking_run_test_progress.setOrientation(QtCore.Qt.Horizontal)
        self.feature_tracking_run_test_progress.setInvertedAppearance(False)
        self.feature_tracking_run_test_progress.setObjectName("feature_tracking_run_test_progress")
        self.horizontalLayout_6.addWidget(self.feature_tracking_run_test_progress)
        self.button_feature_tracking_test = QtWidgets.QPushButton(self.feature_tracking_run_panel)
        self.button_feature_tracking_test.setObjectName("button_feature_tracking_test")
        self.horizontalLayout_6.addWidget(self.button_feature_tracking_test)
        self.gridLayout.addWidget(self.feature_tracking_run_panel, 1, 1, 1, 1)
        self.feature_tracking_video_layout = QtWidgets.QVBoxLayout()
        self.feature_tracking_video_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.feature_tracking_video_layout.setContentsMargins(11, 11, 11, 11)
        self.feature_tracking_video_layout.setSpacing(6)
        self.feature_tracking_video_layout.setObjectName("feature_tracking_video_layout")
        self.gridLayout.addLayout(self.feature_tracking_video_layout, 0, 0, 2, 1)
        self.feature_tracking_parameter_area = QtWidgets.QScrollArea(self.tab_features)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feature_tracking_parameter_area.sizePolicy().hasHeightForWidth())
        self.feature_tracking_parameter_area.setSizePolicy(sizePolicy)
        self.feature_tracking_parameter_area.setMinimumSize(QtCore.QSize(470, 0))
        self.feature_tracking_parameter_area.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.feature_tracking_parameter_area.setWidgetResizable(True)
        self.feature_tracking_parameter_area.setObjectName("feature_tracking_parameter_area")
        self.feature_tracking_parameter_widget = QtWidgets.QWidget()
        self.feature_tracking_parameter_widget.setGeometry(QtCore.QRect(0, 0, 605, 549))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feature_tracking_parameter_widget.sizePolicy().hasHeightForWidth())
        self.feature_tracking_parameter_widget.setSizePolicy(sizePolicy)
        self.feature_tracking_parameter_widget.setObjectName("feature_tracking_parameter_widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.feature_tracking_parameter_widget)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(11, 11, 11, 11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.feature_tracking_parameter_layout = QtWidgets.QHBoxLayout()
        self.feature_tracking_parameter_layout.setContentsMargins(11, 11, 11, 11)
        self.feature_tracking_parameter_layout.setSpacing(6)
        self.feature_tracking_parameter_layout.setObjectName("feature_tracking_parameter_layout")
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.feature_tracking_parameter_layout)
        self.feature_tracking_parameter_area.setWidget(self.feature_tracking_parameter_widget)
        self.gridLayout.addWidget(self.feature_tracking_parameter_area, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.feature_tracking_flow_control = QtWidgets.QFrame(self.tab_features)
        self.feature_tracking_flow_control.setMinimumSize(QtCore.QSize(0, 50))
        self.feature_tracking_flow_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.feature_tracking_flow_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.feature_tracking_flow_control.setObjectName("feature_tracking_flow_control")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.feature_tracking_flow_control)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.feature_tracking_back_button = QtWidgets.QPushButton(self.feature_tracking_flow_control)
        self.feature_tracking_back_button.setObjectName("feature_tracking_back_button")
        self.horizontalLayout_3.addWidget(self.feature_tracking_back_button)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.feature_tracking_continue_button = QtWidgets.QPushButton(self.feature_tracking_flow_control)
        self.feature_tracking_continue_button.setObjectName("feature_tracking_continue_button")
        self.horizontalLayout_3.addWidget(self.feature_tracking_continue_button)
        self.gridLayout_3.addWidget(self.feature_tracking_flow_control, 1, 0, 1, 1)
        self.main_tab_widget.addTab(self.tab_features, "")
        self.roadusers_tab = QtWidgets.QWidget()
        self.roadusers_tab.setObjectName("roadusers_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.roadusers_tab)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.roadusers_tracking_run_panel = QtWidgets.QWidget(self.roadusers_tab)
        self.roadusers_tracking_run_panel.setObjectName("roadusers_tracking_run_panel")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.roadusers_tracking_run_panel)
        self.horizontalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.roadusers_tracking_run_test_progress = QtWidgets.QProgressBar(self.roadusers_tracking_run_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roadusers_tracking_run_test_progress.sizePolicy().hasHeightForWidth())
        self.roadusers_tracking_run_test_progress.setSizePolicy(sizePolicy)
        self.roadusers_tracking_run_test_progress.setProperty("value", 0)
        self.roadusers_tracking_run_test_progress.setOrientation(QtCore.Qt.Horizontal)
        self.roadusers_tracking_run_test_progress.setInvertedAppearance(False)
        self.roadusers_tracking_run_test_progress.setObjectName("roadusers_tracking_run_test_progress")
        self.horizontalLayout_15.addWidget(self.roadusers_tracking_run_test_progress)
        self.button_roadusers_tracking_test = QtWidgets.QPushButton(self.roadusers_tracking_run_panel)
        self.button_roadusers_tracking_test.setObjectName("button_roadusers_tracking_test")
        self.horizontalLayout_15.addWidget(self.button_roadusers_tracking_test)
        self.gridLayout_14.addWidget(self.roadusers_tracking_run_panel, 1, 1, 1, 1)
        self.roadusers_tracking_video_layout = QtWidgets.QVBoxLayout()
        self.roadusers_tracking_video_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.roadusers_tracking_video_layout.setContentsMargins(11, 11, 11, 11)
        self.roadusers_tracking_video_layout.setSpacing(6)
        self.roadusers_tracking_video_layout.setObjectName("roadusers_tracking_video_layout")
        self.gridLayout_14.addLayout(self.roadusers_tracking_video_layout, 0, 0, 2, 1)
        self.roadusers_tracking_parameter_area = QtWidgets.QScrollArea(self.roadusers_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roadusers_tracking_parameter_area.sizePolicy().hasHeightForWidth())
        self.roadusers_tracking_parameter_area.setSizePolicy(sizePolicy)
        self.roadusers_tracking_parameter_area.setMinimumSize(QtCore.QSize(410, 0))
        self.roadusers_tracking_parameter_area.setWidgetResizable(True)
        self.roadusers_tracking_parameter_area.setObjectName("roadusers_tracking_parameter_area")
        self.roadusers_tracking_parameter_widget = QtWidgets.QWidget()
        self.roadusers_tracking_parameter_widget.setGeometry(QtCore.QRect(0, 0, 605, 549))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roadusers_tracking_parameter_widget.sizePolicy().hasHeightForWidth())
        self.roadusers_tracking_parameter_widget.setSizePolicy(sizePolicy)
        self.roadusers_tracking_parameter_widget.setObjectName("roadusers_tracking_parameter_widget")
        self.formLayout_9 = QtWidgets.QFormLayout(self.roadusers_tracking_parameter_widget)
        self.formLayout_9.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_9.setContentsMargins(11, 11, 11, 11)
        self.formLayout_9.setSpacing(6)
        self.formLayout_9.setObjectName("formLayout_9")
        self.roadusers_tracking_parameter_layout = QtWidgets.QHBoxLayout()
        self.roadusers_tracking_parameter_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.roadusers_tracking_parameter_layout.setContentsMargins(11, 11, 0, 11)
        self.roadusers_tracking_parameter_layout.setSpacing(6)
        self.roadusers_tracking_parameter_layout.setObjectName("roadusers_tracking_parameter_layout")
        self.formLayout_9.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.roadusers_tracking_parameter_layout)
        self.roadusers_tracking_parameter_area.setWidget(self.roadusers_tracking_parameter_widget)
        self.gridLayout_14.addWidget(self.roadusers_tracking_parameter_area, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.roadusers_tracking_flow_control = QtWidgets.QFrame(self.roadusers_tab)
        self.roadusers_tracking_flow_control.setMinimumSize(QtCore.QSize(0, 50))
        self.roadusers_tracking_flow_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.roadusers_tracking_flow_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.roadusers_tracking_flow_control.setObjectName("roadusers_tracking_flow_control")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.roadusers_tracking_flow_control)
        self.horizontalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.roadusers_tracking_back_button = QtWidgets.QPushButton(self.roadusers_tracking_flow_control)
        self.roadusers_tracking_back_button.setObjectName("roadusers_tracking_back_button")
        self.horizontalLayout_16.addWidget(self.roadusers_tracking_back_button)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.roadusers_tracking_continue_button = QtWidgets.QPushButton(self.roadusers_tracking_flow_control)
        self.roadusers_tracking_continue_button.setObjectName("roadusers_tracking_continue_button")
        self.horizontalLayout_16.addWidget(self.roadusers_tracking_continue_button)
        self.gridLayout_5.addWidget(self.roadusers_tracking_flow_control, 1, 0, 1, 1)
        self.main_tab_widget.addTab(self.roadusers_tab, "")
        self.tab_results = QtWidgets.QWidget()
        self.tab_results.setObjectName("tab_results")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_results)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.results_grid = QtWidgets.QGridLayout()
        self.results_grid.setContentsMargins(11, 11, 11, 11)
        self.results_grid.setSpacing(6)
        self.results_grid.setObjectName("results_grid")
        self.results_parameter_area = QtWidgets.QScrollArea(self.tab_results)
        self.results_parameter_area.setWidgetResizable(True)
        self.results_parameter_area.setObjectName("results_parameter_area")
        self.results_parameter_widget = QtWidgets.QWidget()
        self.results_parameter_widget.setGeometry(QtCore.QRect(0, 0, 1222, 669))
        self.results_parameter_widget.setObjectName("results_parameter_widget")
        self.formLayoutWidget = QtWidgets.QWidget(self.results_parameter_widget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 261, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.results_parameter_form = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.results_parameter_form.setContentsMargins(11, 11, 11, 11)
        self.results_parameter_form.setSpacing(6)
        self.results_parameter_form.setObjectName("results_parameter_form")
        self.results_parameter_layout = QtWidgets.QHBoxLayout()
        self.results_parameter_layout.setContentsMargins(11, 11, 11, 11)
        self.results_parameter_layout.setSpacing(6)
        self.results_parameter_layout.setObjectName("results_parameter_layout")
        self.results_parameter_form.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.results_parameter_layout)
        self.timeToCollisionLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.timeToCollisionLabel.setObjectName("timeToCollisionLabel")
        self.results_parameter_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.timeToCollisionLabel)
        self.timeToCollisionLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeToCollisionLineEdit.sizePolicy().hasHeightForWidth())
        self.timeToCollisionLineEdit.setSizePolicy(sizePolicy)
        self.timeToCollisionLineEdit.setObjectName("timeToCollisionLineEdit")
        self.results_parameter_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeToCollisionLineEdit)
        self.runAnalysisButton = QtWidgets.QPushButton(self.results_parameter_widget)
        self.runAnalysisButton.setGeometry(QtCore.QRect(10, 60, 261, 32))
        self.runAnalysisButton.setObjectName("runAnalysisButton")
        self.results_parameter_area.setWidget(self.results_parameter_widget)
        self.results_grid.addWidget(self.results_parameter_area, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.results_grid)
        self.main_tab_widget.addTab(self.tab_results, "")
        self.gridLayout_2.addWidget(self.main_tab_widget, 0, 0, 1, 1)
        TransportationSafety.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(TransportationSafety)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuTraffic_Analysis = QtWidgets.QMenu(self.menuBar)
        self.menuTraffic_Analysis.setObjectName("menuTraffic_Analysis")
        self.menuProject = QtWidgets.QMenu(self.menuBar)
        self.menuProject.setObjectName("menuProject")
        self.menuHomography_2 = QtWidgets.QMenu(self.menuProject)
        self.menuHomography_2.setObjectName("menuHomography_2")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        TransportationSafety.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(TransportationSafety)
        self.mainToolBar.setObjectName("mainToolBar")
        TransportationSafety.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(TransportationSafety)
        self.statusBar.setObjectName("statusBar")
        TransportationSafety.setStatusBar(self.statusBar)
        self.actionOpen_Project = QtWidgets.QAction(TransportationSafety)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionAdd_Replace_Video = QtWidgets.QAction(TransportationSafety)
        self.actionAdd_Replace_Video.setObjectName("actionAdd_Replace_Video")
        self.actionFeature_Tracking = QtWidgets.QAction(TransportationSafety)
        self.actionFeature_Tracking.setObjectName("actionFeature_Tracking")
        self.actionRoad_User_Tracking = QtWidgets.QAction(TransportationSafety)
        self.actionRoad_User_Tracking.setObjectName("actionRoad_User_Tracking")
        self.actionLoad_Image = QtWidgets.QAction(TransportationSafety)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionAdd_Replace_Aerial_Image = QtWidgets.QAction(TransportationSafety)
        self.actionAdd_Replace_Aerial_Image.setObjectName("actionAdd_Replace_Aerial_Image")
        self.actionAdd_Replace_Camera_Image = QtWidgets.QAction(TransportationSafety)
        self.actionAdd_Replace_Camera_Image.setObjectName("actionAdd_Replace_Camera_Image")
        self.actionCompute_Homography_Performance = QtWidgets.QAction(TransportationSafety)
        self.actionCompute_Homography_Performance.setObjectName("actionCompute_Homography_Performance")
        self.actionAcquire_Aerial_Image = QtWidgets.QAction(TransportationSafety)
        self.actionAcquire_Aerial_Image.setObjectName("actionAcquire_Aerial_Image")
        self.actionUser_s_Guide = QtWidgets.QAction(TransportationSafety)
        self.actionUser_s_Guide.setObjectName("actionUser_s_Guide")
        self.actionAbout = QtWidgets.QAction(TransportationSafety)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFeedback = QtWidgets.QAction(TransportationSafety)
        self.actionFeedback.setObjectName("actionFeedback")
        self.actionOpen_Video = QtWidgets.QAction(TransportationSafety)
        self.actionOpen_Video.setObjectName("actionOpen_Video")
        self.actionNew_Project = QtWidgets.QAction(TransportationSafety)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.menuTraffic_Analysis.addAction(self.actionNew_Project)
        self.menuTraffic_Analysis.addAction(self.actionOpen_Project)
        self.menuHomography_2.addAction(self.actionAdd_Replace_Aerial_Image)
        self.menuHomography_2.addAction(self.actionAdd_Replace_Camera_Image)
        self.menuHomography_2.addSeparator()
        self.menuHomography_2.addAction(self.actionCompute_Homography_Performance)
        self.menuHomography_2.addAction(self.actionAcquire_Aerial_Image)
        self.menuProject.addAction(self.menuHomography_2.menuAction())
        self.menuHelp.addAction(self.actionUser_s_Guide)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuTraffic_Analysis.menuAction())
        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(TransportationSafety)
        self.main_tab_widget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(TransportationSafety)

    def retranslateUi(self, TransportationSafety):
        _translate = QtCore.QCoreApplication.translate
        TransportationSafety.setWindowTitle(_translate("TransportationSafety", "Transportation Safety"))
        self.homography_button_open_camera_image.setText(_translate("TransportationSafety", "Open Camera Image"))
        self.homography_button_open_aerial_image.setText(_translate("TransportationSafety", "Open Aerial Image"))
        self.homography_label_zoom_camera_image.setText(_translate("TransportationSafety", "Zoom:"))
        self.homography_label_zoom_computed_image.setText(_translate("TransportationSafety", "Zoom:"))
        self.homography_label_zoom_aerial_image.setText(_translate("TransportationSafety", "Zoom:"))
        self.unit_px_label.setText(_translate("TransportationSafety", "Unit Pixel Ratio:"))
        self.unit_px_label2.setText(_translate("TransportationSafety", "m/px"))
        self.homography_compute_button.setText(_translate("TransportationSafety", "Compute Homography"))
        self.homography_continue_button.setText(_translate("TransportationSafety", " Continue >"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.tab_homography), _translate("TransportationSafety", "Homography"))
        self.feature_tracking_run_test_progress.setFormat(_translate("TransportationSafety", "%p%"))
        self.button_feature_tracking_test.setText(_translate("TransportationSafety", "Test on Sample"))
        self.feature_tracking_back_button.setText(_translate("TransportationSafety", "< Homography"))
        self.feature_tracking_continue_button.setText(_translate("TransportationSafety", " Continue >"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.tab_features), _translate("TransportationSafety", "Track Features"))
        self.roadusers_tracking_run_test_progress.setFormat(_translate("TransportationSafety", "%p%"))
        self.button_roadusers_tracking_test.setText(_translate("TransportationSafety", "Test on Sample"))
        self.roadusers_tracking_back_button.setText(_translate("TransportationSafety", "<Track Features"))
        self.roadusers_tracking_continue_button.setText(_translate("TransportationSafety", " Continue >"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.roadusers_tab), _translate("TransportationSafety", "Track Road Users"))
        self.timeToCollisionLabel.setText(_translate("TransportationSafety", "time to collision"))
        self.timeToCollisionLineEdit.setText(_translate("TransportationSafety", "1.5"))
        self.runAnalysisButton.setText(_translate("TransportationSafety", "Run Video Analysis"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.tab_results), _translate("TransportationSafety", "Results"))
        self.menuTraffic_Analysis.setTitle(_translate("TransportationSafety", "File"))
        self.menuProject.setTitle(_translate("TransportationSafety", "Project"))
        self.menuHomography_2.setTitle(_translate("TransportationSafety", "Homography"))
        self.menuHelp.setTitle(_translate("TransportationSafety", "Help"))
        self.actionOpen_Project.setText(_translate("TransportationSafety", "Open Project"))
        self.actionOpen_Project.setShortcut(_translate("TransportationSafety", "Ctrl+O"))
        self.actionAdd_Replace_Video.setText(_translate("TransportationSafety", "Video"))
        self.actionFeature_Tracking.setText(_translate("TransportationSafety", "Feature Tracking"))
        self.actionRoad_User_Tracking.setText(_translate("TransportationSafety", "Road-User Tracking"))
        self.actionLoad_Image.setText(_translate("TransportationSafety", "Load Image"))
        self.actionLoad_Image.setShortcut(_translate("TransportationSafety", "Ctrl+I"))
        self.actionAdd_Replace_Aerial_Image.setText(_translate("TransportationSafety", "Add/Replace Aerial Image"))
        self.actionAdd_Replace_Camera_Image.setText(_translate("TransportationSafety", "Add/Replace Camera Image"))
        self.actionCompute_Homography_Performance.setText(_translate("TransportationSafety", "Compute Homography Performance"))
        self.actionAcquire_Aerial_Image.setText(_translate("TransportationSafety", "Acquire Aerial Image"))
        self.actionUser_s_Guide.setText(_translate("TransportationSafety", "User\'s Guide"))
        self.actionAbout.setText(_translate("TransportationSafety", "About"))
        self.actionFeedback.setText(_translate("TransportationSafety", "Send Feedback"))
        self.actionOpen_Video.setText(_translate("TransportationSafety", "Open Video"))
        self.actionNew_Project.setText(_translate("TransportationSafety", "New Project"))
        self.actionNew_Project.setShortcut(_translate("TransportationSafety", "Ctrl+N"))

from custom.homography import HomographyResultView, HomographyView
from custom.zoomslider import ZoomSlider
